CREATE TABLE tests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER REFERENCES courses(id) ON DELETE SET NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    time_limit INTEGER NOT NULL,
    total_marks NUMERIC(10,2) NOT NULL DEFAULT 0,
    negative_marking_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    negative_mark_value NUMERIC(10,2) NOT NULL DEFAULT 0,
    strict_mode_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    max_tab_switch INTEGER NOT NULL DEFAULT 0,
    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    section_order INTEGER NOT NULL,
    CONSTRAINT uq_sections_test_order UNIQUE (test_id, section_order)
);

CREATE TABLE questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id INTEGER NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    question_type VARCHAR(20) NOT NULL CHECK (question_type IN ('MCQ', 'TRUE_FALSE', 'FILL')),
    marks NUMERIC(10,2) NOT NULL DEFAULT 1,
    correct_answer TEXT,
    explanation TEXT,
    question_order INTEGER NOT NULL,
    CONSTRAINT uq_questions_section_order UNIQUE (section_id, question_order)
);

CREATE TABLE options (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    option_text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE test_attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    score NUMERIC(10,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'SUBMITTED', 'AUTO_SUBMITTED')),
    tab_switch_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id INTEGER NOT NULL REFERENCES test_attempts(id) ON DELETE CASCADE,
    question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    selected_option_id INTEGER REFERENCES options(id) ON DELETE SET NULL,
    text_answer TEXT,
    is_marked_for_review BOOLEAN NOT NULL DEFAULT FALSE,
    is_answered BOOLEAN NOT NULL DEFAULT FALSE,
    saved_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_answers_attempt_question UNIQUE (attempt_id, question_id)
);

CREATE TABLE section_progress (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id INTEGER NOT NULL REFERENCES test_attempts(id) ON DELETE CASCADE,
    section_id INTEGER NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_section_progress_attempt_section UNIQUE (attempt_id, section_id)
);

CREATE TABLE leaderboard (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score NUMERIC(10,2) NOT NULL DEFAULT 0,
    rank INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_leaderboard_test_user UNIQUE (test_id, user_id)
);

CREATE INDEX idx_tests_course_id ON tests(course_id);
CREATE INDEX idx_sections_test_id ON sections(test_id);
CREATE INDEX idx_questions_section_id ON questions(section_id);
CREATE INDEX idx_options_question_id ON options(question_id);
CREATE INDEX idx_attempts_test_user ON test_attempts(test_id, user_id);
CREATE INDEX idx_attempts_status ON test_attempts(status);
CREATE INDEX idx_answers_attempt_id ON answers(attempt_id);
CREATE INDEX idx_section_progress_attempt_id ON section_progress(attempt_id);
CREATE INDEX idx_leaderboard_test_rank ON leaderboard(test_id, rank);
