CREATE TABLE test_enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
    enrolled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_test_enrollments_user_test UNIQUE (user_id, test_id)
);

CREATE INDEX idx_test_enrollments_user_id ON test_enrollments(user_id);
CREATE INDEX idx_test_enrollments_test_id ON test_enrollments(test_id);
